--[[
************************************************************************
ptBR.lua
ptBR localization strings for Collectinator
************************************************************************
File date: 2012-09-12T01:10:19Z 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: 2.0.10
************************************************************************
Currently maintained by:
http://www.wowace.com/addons/collectinator/localization/translators/

Please update http://www.wowace.com/addons/collectinator/localization/ptBR/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.

Please make sure you update the ToC file with any translations.
************************************************************************
Please see http://www.wowace.com/addons/collectinator/ for more information.
************************************************************************
These translations are released under the Public Domain.
************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "ptBR", false)

if not L then return end

L["Aldraan"] = true -- Needs review
L["Bana Wildmane"] = "Bana Juba Agreste" -- Needs review
L["Belbi Quikswitch"] = "Bebel Trocarrápida" -- Needs review
L["Blix Fixwidget"] = "Blix Consertatreco" -- Needs review
L["Bogflare Needler"] = "Agulheiro Brejolume" -- Needs review
L["Breanni"] = true -- Needs review
L["Briarthorn"] = "Cravespinho" -- Needs review
L["Brunn Flamebeard"] = "Bruno Barbachama" -- Needs review
L["Cielstrasza"] = true -- Needs review
L["Coreiel"] = true -- Needs review
L["Corporal Arthur Flew"] = "Cabo Arthur Volus" -- Needs review
L["Dama Wildmane"] = "Dara Juba Agreste" -- Needs review
L["Dame Evniki Kapsalis"] = "Dama Evniki Kapsalis" -- Needs review
L["Darahir"] = true -- Needs review
L["Dealer Rashaad"] = "Mercador Rashaad" -- Needs review
L["Defias Pirate"] = "Pirata Défias" -- Needs review
L["Demisette Cloyce"] = "Joyce Lopes" -- Needs review
L["Derrick Brindlebeard"] = "Derico Barbalistra" -- Needs review
L["Deviate Guardian"] = "Guardião Anormal" -- Needs review
L["Deviate Ravager"] = "Assolador Anormal" -- Needs review
L["Dhugru Gorelust"] = "Dhugru Gostassangue" -- Needs review
L["Donni Anthania"] = "Cristiana Justa" -- Needs review
L["Doru Thunderhorn"] = "Doru Chifre Troante" -- Needs review
L["Drake Dealer Hurlunk"] = "Comerciante de Dracos Hurlunk" -- Needs review
L["Dread Commander Thalanor"] = "Terrível Comandante Thalanor" -- Needs review
L["Driz Tumblequick"] = "Driz Topalogo" -- Needs review
L["Durgan Thunderbeak"] = "Durgan Rostrovão" -- Needs review
L["Eliza Killian"] = "Elisa Morgado" -- Needs review
L["Fedryen Swiftspear"] = "Fedryen Lancélere" -- Needs review
L["Flik"] = true -- Needs review
L["Freka Bloodaxe"] = "Freiga Machado Sangrento" -- Needs review
L["Gaelden Hammersmith"] = "Gaelden Marteleiro" -- Needs review
L["Geen"] = true -- Needs review
L["Gregor MacVince"] = true -- Needs review
L["Grella"] = "Drella" -- Needs review
