-- a grave 195.160
-- a circumflex	195.162
-- e circumflex 195.170
-- e grave 195.168
-- e acute 195.169

FishingTranslations["frFR"] = {
	ABOUT_TAB = "A propos", -- Needs review
	ADDFISHIEMSG = "Ajout de %s au lieu %s.",
	ADDSCHOOLMSG = "Ajout de '%s' au lieu %s.",
	ALLZOMGPETS = "Inclure toutes mascottes", -- Needs review
	BINDING_NAME_FISHINGBUDDY_GOFISHING = "S'habiller et aller p\195\170cher",
	BINDING_NAME_FISHINGBUDDY_SWITCH = "Porter l'\195\169quipement de p\195\170che", -- Needs review
	BINDING_NAME_FISHINGBUDDY_TOGGLE = "Activer la fen\195\170tre #NAME#", -- Needs review
	BINDING_NAME_TOGGLEFISHINGBUDDY_LOC = "Activer le panneau de r\195\169gion #NAME#", -- Needs review
	BINDING_NAME_TOGGLEFISHINGBUDDY_OPT = "Activer le panneau d'options #NAME#",
	BOBBER_NAME = "Bouchon",
	CAUGHT_IN_ZONES = "Pris \195\160 :",
	CAUGHTTHISMANY = "Pris :",
	CAUGHTTHISTOTAL = "Total :",
	CLEANUP_DONEMSG = "Anciens param\195\168tres supprim\195\169s pour |c#RED#%s|r: %s.",
	CLEANUP_NONEMSG = "Il ne reste plus d'anciens r\195\169glages.",
	CLEANUP_NOOLDMSG = "Il n'y a pas d'ancien r\195\169glages pour le joueur |c#GREEN#%s|r.",
	CLEANUP_WILLMSG = "Ancien r\195\169glages supprim\195\169s pour |c#RED#%s|r: %s.",
	CLICKTOSWITCH_INFO = "Si actif, un clic gauche change l'\195\169quipement, sinon, il affiche la fen\195\170tre Fishing Buddy.", -- Needs review
	CLICKTOSWITCH_ONOFF = "Cliquer pour changer",
	COMPATIBLE_SWITCHER = "Trouv\195\169 aucune tenue compatible \195\160 mettre.", -- Needs review
	CONFIG_ALWAYSLURE_INFO = "Si activ\195\169, appliquer un app\195\162t si aucun n'est d\195\169j\195\160 pr\195\169sent.", -- Needs review
	CONFIG_ALWAYSLURE_ONOFF = "Mettre app\195\162t", -- Needs review
	CONFIG_AUTOLOOT_INFO = "Si activ\195\169, ferrage automatiquement le poisson durant la p\195\170che.", -- Needs review
	CONFIG_AUTOLOOT_INFOD = "Le ferrage automatique est d\195\169sactiv\195\169e car FishWarden est activ\195\169.", -- Needs review
	CONFIG_AUTOLOOT_ONOFF = "Ferrage auto", -- Needs review
	CONFIG_AUTOOPEN_INFO = "Si actif, faire un double-clic pour ouvrir les objets de qu\195\170te de p\195\170che.", -- Needs review
	CONFIG_AUTOOPEN_ONOFF = "Ouvrir les objets de qu\195\170te", -- Needs review
	CONFIG_BGSOUNDS_INFO = "Si activ\195\169, le son sera actif tandis que WoW est en arri\195\168re-plan.", -- Needs review
	CONFIG_BGSOUNDS_ONOFF = "Son en arri\195\168re-plan", -- Needs review
	-- CONFIG_BOBBINGBERG_INFO = "If enabled, using the bobbing berg.",
	CONFIG_CONTESTS_INFO = "Afficher le compte \195\160 rebour pour les concours de p\195\170che.", -- Needs review
	CONFIG_CONTESTS_ONOFF = "Soutien au concours de p\195\170che", -- Needs review
	-- CONFIG_CREATEMACRO_INFO = "Create a macro that performs #NAME# functions.",
	-- CONFIG_CREATEMACRO_ONOFF = "Create macro",
	CONFIG_DERBYTIMER_INFO = "Si actif, affiche un compte \195\160 rebours jusqu'au d\195\169but du Tournoi de p\195\170che kalu'ak, puis un compte \195\160 rebours du temps restant.", -- Needs review
	CONFIG_DERBYTIMER_ONOFF = "compte \195\160 rebours du match", -- Needs review
	-- CONFIG_DINGQUESTFISH_INFO = "If enabled, the quest added sound will play when a Nat Pagle reputation fish is caught.",
	-- CONFIG_DINGQUESTFISH_ONOFF = "Fish Ringer",
	CONFIG_DRINKHEAVILY_INFO = "Si actif, boire une #LAGER# chaque fois que vous p\195\170chez et redevenez \194\171 sobre \194\187.", -- Needs review
	CONFIG_DRINKHEAVILY_ONOFF = "Boire une bi\195\168re", -- Needs review
	CONFIG_EASYCAST_INFO = "Active le lancer de bouchon par double-clic-droit.",
	CONFIG_EASYCAST_INFOD = "Le lanc\195\169 facile est d\195\169sactiv\195\169 car Fishing Ace! est activ\195\169.", -- Needs review
	CONFIG_EASYCASTKEYS_INFO = "Si une touche de modification est sp\195\169cifi\195\169e et quand elle est enfonc\195\169e, sans distinction de l'\195\169quipement de p\195\170che.", -- Needs review
	CONFIG_EASYCAST_ONOFF = "Lancer le bouchon facilement",
	CONFIG_EASYLURES_INFO = "Si actif, un app\195\162t sera appliqu\195\169 \195\160 votre canne \195\160 p\195\170che avant de commencer la p\195\170che et chaque fois que vous en aurez besoin.", -- Needs review
	CONFIG_EASYLURES_ONOFF = "App\195\162ts faciles",
	CONFIG_ENHANCESOUNDS_INFO = "Si actif, augmente le volume des sons et baisse les volumes de l'ambiance afin de mieux entendre le bouchon.",
	CONFIG_ENHANCESOUNDS_ONOFF = "Augmente les bruits de p\195\170che", -- Needs review
	CONFIG_FINDFISH_INFO = "Activer le pistage \194\171 D\195\169couverte de poissons \194\187 lorsque l'on est \195\169quip\195\169 pour la p\195\170che.", -- Needs review
	CONFIG_FINDFISH_ONOFF = "Trouver des poissons",
	CONFIG_FISHINGBUDDY_INFO = "Invoque la mascotte sp\195\169ciale pendant que vous p\195\170che.", -- Needs review
	CONFIG_FISHINGBUDDY_ONOFF = "Fishing Buddy", -- Needs review
	-- CONFIG_FISHINGCHARM_INFO = "If enabled, use the fishing charm while in Pandaria.",
	CONFIG_FISHINGFLUFF_INFO = "Activer toutes sortes de plaisir alors que vous p\195\170chez.", -- Needs review
	CONFIG_FISHINGFLUFF_ONOFF = "P\195\170che amusante", -- Needs review
	-- CONFIG_FISHINGRAFT_INFO = "If enabled, use the fishing raft.",
	CONFIG_FISHWATCH_INFO = "Affiche une zone de texte avec les poissons d\195\169j\195\160 p\195\170ch\195\169s dans la zone courante.", -- Needs review
	CONFIG_FISHWATCHONLY_INFO = "Montrer seulement les poissons lorsque vous \195\170tes en train de p\195\170cher.", -- Needs review
	CONFIG_FISHWATCHONLY_ONOFF = "Uniquement en p\195\170chant", -- Needs review
	CONFIG_FISHWATCH_ONOFF = "Archive des poissons",
	-- CONFIG_FISHWATCHPAGLE_INFO = "Display which Pagle quest fish you have caught today.",
	-- CONFIG_FISHWATCHPAGLE_ONOFF = "Watch Pagle's Fish",
	CONFIG_FISHWATCHPERCENT_INFO = "Affiche les pourcentages pour chaque type de poisson dans la zone de texte.",
	CONFIG_FISHWATCHPERCENT_ONOFF = "Montre les pourcentages",
	CONFIG_FISHWATCHSKILL_INFO = "Affiche votre niveau de p\195\170che actuel ainsi que les am\195\169liorations dans la zone de texte.", -- Needs review
	CONFIG_FISHWATCHSKILL_ONOFF = "Niveau actuel",
	CONFIG_FISHWATCHTIME_INFO = "Afficher le temps \195\169coul\195\169 depuis la derni\195\168re fois qu'une canne \195\160 p\195\170che a \195\169t\195\169 \195\169quip\195\169e", -- Needs review
	CONFIG_FISHWATCHTIME_ONOFF = "Afficher le temps \195\169coul\195\169",
	CONFIG_FISHWATCHZONE_INFO = "Affiche la zone courante dans la zone de texte.",
	CONFIG_FISHWATCHZONE_ONOFF = "Zone courante",
	CONFIG_LASTRESORT_INFO = "Si actif, ajoute le plus grand app\195\162t m\195\170me si l'on n'a pas 100 % de chances de ferrer du poisson.", -- Needs review
	CONFIG_LASTRESORT_ONOFF = "App\195\162t en dernier recours", -- Needs review
	-- CONFIG_MAINTAINBERG_INFO = "If enabled, do not use the bobbing berg item, only maintain it if it is already being used.",
	-- CONFIG_MAINTAINRAFTBERG_ONOFF = "Maintain only",
	-- CONFIG_MAINTAINRAFT_INFO = "If enabled, do not use the raft item, only maintain it if it is already being used.",
	CONFIG_MAXSOUND_INFO = "Si actif, r\195\168gle le volume sonore au maximum durant la p\195\170che.", -- Needs review
	CONFIG_MAXSOUND_ONOFF = "Volume au maximum", -- Needs review
	CONFIG_MINIMAPBUTTON_INFO = "Affiche le bouton de #NAME# autour de la minimap.",
	CONFIG_MINIMAPBUTTON_ONOFF = "Affiche le bouton de la minimap.",
	CONFIG_MINIMAPMOVE_INFO = "Si actif, l'ic\195\180ne de la minicarte peut \195\170tre d\195\169plac\195\169e par glissement.", -- Needs review
	CONFIG_MINIMAPMOVE_ONOFF = "D\195\169pla\195\167able", -- Needs review
	CONFIG_MOUNTEDCAST_INFO = "Si actif, lance la ligne quand mont\195\169.", -- Needs review
	CONFIG_MOUNTEDCAST_ONOFF = "Mont\195\169", -- Needs review
	-- CONFIG_MOUSEEVENT_INFO = "Use this mouse button to cast.",
	-- CONFIG_MOUSEEVENT_ONOFF = "Casting Button",
	CONFIG_ONLYMINE_INFO = "Si actif, le lanc\195\169 facile sera v\195\169rifi\195\169 uniquement pour votre canne \195\160 p\195\170che sur votre tenue (c'est-\195\160-dire qu'il ne recherche pas toutes les cannes possibles pour une partie de p\195\170che).", -- Needs review
	CONFIG_ONLYMINE_ONOFF = "Tenue de canne \195\160 p\195\170che uniquement", -- Needs review
	CONFIG_OUTFITTER_TEXT = "Bonus de comp\195\169tence de tenue : %s#BR#Tel que le score de Draznar : %d ", -- Needs review
	CONFIG_PARTIALGEAR_INFO = "Si activ\195\169, lanc\195\169 lorsque vous portez au moins une seule tenue de p\195\170che, m\195\170me si une canne n'est pas \195\169quip\195\169e.", -- Needs review
	CONFIG_PARTIALGEAR_ONOFF = "Tenue partielle", -- Needs review
	-- CONFIG_PREVENTRECAST_INFO = "Invoking the macro while fishing will not cast again. Lures will be reapplied if needed.",
	-- CONFIG_PREVENTRECAST_ONOFF = "Prevent recast",
	CONFIG_SHOWLOCATIONZONES_INFO = "Afficher les zones et sous-zones.", -- Needs review
	CONFIG_SHOWLOCATIONZONES_ONOFF = "Affiche les zones", -- Needs review
	CONFIG_SHOWNEWFISHIES_INFO = "Affiche un message dans la zone de texte quand un nouveau poisson est p\195\170ch\195\169.", -- Needs review
	CONFIG_SHOWNEWFISHIES_ONOFF = "Montrer les nouveaux poissons",
	CONFIG_SHOWPOOLS_INFO = "Si actif, les emplacements connus des bancs seront affich\195\169s sur la minicarte.", -- Needs review
	CONFIG_SHOWPOOLS_ONOFF = "Afficher les bancs", -- Needs review
	CONFIG_SORTBYPERCENT_INFO = "Trier par quantit\195\169 de poissons p\195\170ch\195\169s plut\195\180t que par ordre alphab\195\169tique.", -- Needs review
	CONFIG_SORTBYPERCENT_ONOFF = "Trie par quantit\195\169 de poissons", -- Needs review
	CONFIG_SPARKLIES_INFO = "Si actif, les \194\171 scintillement \194\187 dans les bancs de p\195\170che seront plus visible durant la p\195\170che.", -- Needs review
	CONFIG_SPARKLIES_ONOFF = "Bancs am\195\169lior\195\169s", -- Needs review
	CONFIG_STVPOOLSONLY_INFO = "Si actif, lanc\195\169 facile possible seulement quand le curseur survol un banc de poissons.", -- Needs review
	CONFIG_STVPOOLSONLY_ONOFF = "Lanc\195\169 uniquement sur l'eau", -- Needs review
	CONFIG_STVTIMER_INFO = "Si actif, un compteur sera affich\195\169 indiquant le temps restant avant le d\195\169but et avant la fin du concours.", -- Needs review
	CONFIG_STVTIMER_ONOFF = "Compte \195\160 rebours du concours de p\195\170che", -- Needs review
	CONFIG_TOOLTIPS_INFO = "Si actif, les informations sur les poissons attrap\195\169s seront affich\195\169es en info-bulle.", -- Needs review
	CONFIG_TOOLTIPS_ONOFF = "Affiche les infos de p\195\170che en info-bulle.", -- Needs review
	-- CONFIG_TOONMACRO_INFO = "Create the fishing macro per player.",
	-- CONFIG_TOONMACRO_ONOFF = "Per player",
	CONFIG_TURNOFFPVP_INFO = "Si actif, le JcJ sera d\195\169sactiv\195\169 d\195\168s qu'une canne \195\160 p\195\170che sera \195\169quip\195\169e.", -- Needs review
	CONFIG_TURNOFFPVP_ONOFF = "D\195\169sactive le JcJ", -- Needs review
	CONFIG_TURNONSOUND_INFO = "Si actif, toujours avoir les sons durant la p\195\170che.", -- Needs review
	CONFIG_TURNONSOUND_ONOFF = "Forcer le son", -- Needs review
	-- CONFIG_TUSKAARSPEAR_INFO = "If enabled, do the complicated dance to use the Tuskaar Spear.",
	CONFIG_USEACTION_INFO = "Si actif, #NAME# va chercher \195\160 utiliser un bouton de la barre d'action pour le lanc\195\169.", -- Needs review
	CONFIG_USEACTION_ONOFF = "Utiliser Action", -- Needs review
	CONFIG_WATCHBOBBER_INFO = "Si actif, #NAME# ne sera pas lanc\195\169 si le curseur est sur le flotteur de p\195\170che.", -- Needs review
	-- CONFIG_WATCHBOBBER_ONOFF = "Watch bobber",
	COPPER_COIN = "Pi\195\168ce de cuivre", -- Needs review
	CURRENT_HELP = "|c#GREEN#/fb #CURRENT# #RESET#|r#BRSPCS#Remet a z\195\169ro les poissons pris au cours de cette session.", -- Needs review
	DERBY = "Match", -- Needs review
	DESCRIPTION1 = "Se souvient des poissons pris et",
	DESCRIPTION2 = "organise votre \195\169quipement.", -- Needs review
	ELAPSED = "Ecoul\195\169", -- Needs review
	ELDER_CLEARWATER = "Ancien Clairdeleau crie : (%a)+ a remport\195\169 le tournoi de p\195\170che kalu'ak !", -- Needs review
	ELEM_WATER = "El\195\169mentaire d'eau", -- Needs review
	EXTRAVAGANZA = "Le concours de p\195\170che", -- Needs review
	FAILEDINIT = "Ne s'est pas initialis\195\169 correctement.", -- Needs review
	FATLADYSINGS = "|c#RED#%s est fait|r (%d:%02d restant)", -- Needs review
	FISH = "Poisson", -- Needs review
	-- FISHINGMODE_HELP = "|c#GREEN#/fb #FISHINGMODE# [start|stop]|r#BRSPCS#Run #NAME# fishing actions.#BRSPCS#Useful in macros along with '/cast Fishing'.",
	FISHTYPES = "Genres de poissons", -- Needs review
	FLOATING_DEBRIS = "D\195\169bris flottant", -- Needs review
	FLOATING_WRECKAGE = "Epave flottante", -- Needs review
	GOLD_COIN = "Pi\195\168ce d'or", -- Needs review
	HIDEINWATCHER = "Afficher ce poisson dans l'afficheur", -- Needs review
	KEYS_ALT_TEXT = "Alt", -- Needs review
	KEYS_CTRL_TEXT = "CTRL",
	KEYS_LABEL_TEXT = "Touches :",
	KEYS_NONE_TEXT = "Aucune",
	KEYS_SHIFT_TEXT = "Maj.", -- Needs review
	LAGER = "Brune du capitaine Rumsey",
	LEFTCLICKTODRAG = "Clic-gauche pour d\195\169placer", -- Needs review
	LOCATIONS_INFO = "Affiche les informations de p\195\170che locales", -- Needs review
	LOCATIONS_TAB = "Lieux",
	-- MACRONAME = "FishingBuddy",
	MINIMAPBUTTONPLACEMENT = "Position du bouton",
	MINIMAPBUTTONPLACEMENTTOOLTIP = "Permet de d\195\169placer le bouton de #NAME# autour de la minimap", -- Needs review
	MINIMAPBUTTONRADIUS = "Distance", -- Needs review
	MINIMAPBUTTONRADIUSTOOLTIP = "D\195\169termine \195\160 quelle distance de la minicarte l'ic\195\180ne #NAME# doit \195\170tre.", -- Needs review
	MINIMUMSKILL = "Comp\195\169tence minimum : %d", -- Needs review
	NAME = "Fishing Buddy", -- Needs review
	-- NOCREATEMACROGLOB = "Could not create global macro: ",
	-- NOCREATEMACROPER = "Could not create per character macro: ",
	NODATAMSG = "Aucune donn\195\169e de p\195\170che disponible.", -- Needs review
	NONEAVAILABLE_MSG = "Pas disponible", -- Needs review
	NOREALM = "royaume inconnu", -- Needs review
	NOTLINKABLE = "<objet non linkable>", -- Needs review
	-- OFFSET_LABEL_TEXT = "Offset:",
	-- OIL_SPILL = "Oil Spill",
	OPTIONS_INFO = "R\195\169gler les options #NAME# ", -- Needs review
	OPTIONS_TAB = "Options", -- Needs review
	OUTFITS = "Tenues", -- Needs review
	POINT = "point", -- Needs review
	POINTS = "points", -- Needs review
	POST_HELP = "Vous pouvez assigner une touche pour afficher/cacher la fen\195\170tre et/ou#BR#changer d'\195\169quipement dans la fen\195\170tre \194\171 Raccourcis \194\187.", -- Needs review
	PRE_HELP = "Vous pouvez utiliser |c#GREEN#/fishingbuddy|r ou |c#GREEN#/fb|r pour toutes les commandes#BR#|c#GREEN#/fb|r: seul, affiche/cache la fen\195\170tre de FishingBuddy#BR#|c#GREEN#/fb #HELP#|r: affiche ce message", -- Needs review
	RANDOM = "Al\195\169atoire", -- Needs review
	RAW = "basse qualit\195\169", -- Needs review
	RIGGLE_BASSBAIT = "Riggle Perchapp\195\162t crie : \194\171 Nous avons un gagnant ! (%a+) est le Ma\195\174tre p\195\170cheur ! \194\187", -- Needs review
	RIGHTCLICKFORMENU = "Cliquer-droit pour le menu", -- Needs review
	ROLE_ADDON_AUTHORS = "Auteur des notes de l'addon", -- Needs review
	ROLE_HELP_BUGS = "Aide", -- Needs review
	ROLE_HELP_SUGGESTIONS = "Suggestions particuli\195\168res", -- Needs review
	ROLE_TRANSLATE_DEDE = "Traduction allemande", -- Needs review
	ROLE_TRANSLATE_ESES = "Traduction espagnole", -- Needs review
	ROLE_TRANSLATE_FRFR = "Traduction fran\195\167aise", -- Needs review
	ROLE_TRANSLATE_ITIT = "Traduction italienne", -- Needs review
	ROLE_TRANSLATE_KOKR = "Traduction cor\195\169enne", -- Needs review
	ROLE_TRANSLATE_PTBR = "Traduction br\195\169silienne-portugaise", -- Needs review
	ROLE_TRANSLATE_RURU = "Traduction russe", -- Needs review
	ROLE_TRANSLATE_ZHCN = "Traduction chinoise simplifi\195\169e", -- Needs review
	ROLE_TRANSLATE_ZHTW = "Traduction chinoise traditionnelle", -- Needs review
	SCHOOL = "Ecole", -- Needs review
	SHOWFISHIES = "Poissons", -- Needs review
	SHOWFISHIES_INFO = "Affiche vos prises class\195\169es par type de poisson.", -- Needs review
	SHOWLOCATIONS = "Lieux",
	SHOWLOCATIONS_INFO = "Affiche vos prises class\195\169es par lieux.", -- Needs review
	SILVER_COIN = "Pi\195\168ce d'argent", -- Needs review
	STVZONENAME = "Vall\195\169e de Strangleronce", -- Needs review
	SWITCH_HELP = "|c#GREEN#/fb #SWITCH#|r#BRSPCS#Change l'\195\169quipement (si OutfitDisplayFrame ou Outfitter est charg\195\169)", -- Needs review
	THANKS = "Merci \195\160 tous !", -- Needs review
	TIMELEFT = "%s se termine dans %d:%02d",
	TIMERRESET_HELP = "|c#GREEN#/fb #TIMER# #RESET#|r#BRSPCS#R\195\169initialiser l'emplacement du compteur Extravaganza#BRSPCS#en la d\195\169pla\195\167ant vers le centre de l'\195\169cran.", -- Needs review
	TIMETOGO = "%s commence dans %d:%02d",
	TOOLTIP_HINT = "Astuce :", -- Needs review
	TOOLTIP_HINTSWITCH = "Cliquer pour mettre une autre tenue", -- Needs review
	TOOLTIP_HINTTOGGLE = "cliquer pour afficher la fen\195\170tre #NAME#.", -- Needs review
	TOOMANYFISHERMEN = "Vous avez plus d'une sorte de lancement facile d'install\195\169.", -- Needs review
	TOTAL = "Total", -- Needs review
	TOTALS = "Totaux", -- Needs review
	UPDATEDB_HELP = "|c#GREEN#/fb #UPDATEDB# [#FORCE#]|r#BRSPCS#Tentative de trouver les noms de tous les poissons que#BRSPCS#nous n'avons pas. Une tentative est faite pour passer les poissons \194\171 rare \194\187 qui peuvent vous d\195\169connecter du serveur ; utiliser l'option \194\171 #FORCE# \194\187 pour remplacer la v\195\169rification.", -- Needs review
	UPDATEDB_MSG = "Mise \195\160 jour de %d noms de poisson.", -- Needs review
	WATCHER_HELP = "|c#GREEN#/fb #WATCHER#|r [|c#GREEN##WATCHER_LOCK#|r or |c#GREEN##WATCHER_UNLOCK#|r or |c#GREEN##RESET#|r]#BRSPCS#D\195\169verrouille pour bouger la fen\195\170tre,#BRSPCS#lock pour la bloquer, reset pour remettre en position par d\195\169faut", -- Needs review
	-- WATCHER_TAB = "Watcher",
}